platform/lib/platform_web/router.ex
defmodule PlatformWeb.Router do
  use PlatformWeb, :router

  import PlatformWeb.UserAuth
  import PlatformWeb.APIAuth
  alias PlatformWeb.MountHelperLive

  pipeline :browser do
    plug(RemoteIp)
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {PlatformWeb.LayoutView, :root})
    plug(:protect_from_forgery)

    plug(:put_secure_browser_headers, %{
      # TODO: There are opportunities to make this content security policy stricter (specifically by adding
      # `default-src 'none'` and removing cdn.jsdelivr.net); this is an opportunity for future improvement. To
      # quote Sobelow, just about any CSP is better than the default (no CSP at all!).
      "content-security-policy" =>
        "object-src 'none'; script-src 'self' api.mapbox.com js.stripe.com hcaptcha.com *.hcaptcha.com unpkg.com static.highlight.io 'unsafe-eval' blob:; base-uri 'none'; worker-src blob: 'self'; child-src blob: 'self' hcaptcha.com *.hcaptcha.com js.stripe.com;"
    })

    plug(:fetch_current_user)
  end

  pipeline :app do
    plug(:put_layout, {PlatformWeb.LayoutView, "interstitial.html"})
  end

  pipeline :interstitial do
    plug(:put_layout, {PlatformWeb.LayoutView, "interstitial.html"})
  end

  pipeline :interstitial_minimal do
    plug(:put_layout, {PlatformWeb.LayoutView, "interstitial_minimal.html"})
  end

  pipeline :api do
    plug(RemoteIp)
    plug(:accepts, ["json"])
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through(:browser)

      live_dashboard("/dashboard",
        metrics: PlatformWeb.Telemetry,
        additional_pages: [
          flame_on: FlameOn.DashboardPage
        ]
      )
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through(:browser)

      forward("/mailbox", Plug.Swoosh.MailboxPreview)
    end
  end

  scope "/api", PlatformWeb do
    pipe_through([:api, :check_api_token])

    scope "/v1" do
      pipe_through([:require_legacy_token])

      get("/media_versions", APIV1Controller, :media_versions)
      get("/media", APIV1Controller, :media)
    end

    scope "/v2" do
      pipe_through([:require_project_scoped_token])

      get("/source_material", APIV2Controller, :media_versions)
      get("/source_material/:id", APIV2Controller, :media_version)
      post("/source_material/new/:slug", APIV2Controller, :create_media_version)
      post("/incidents/new", APIV2Controller, :create_media)

      post(
        "/source_material/metadata/:id/:namespace",
        APIV2Controller,
        :set_media_version_metadata
      )

      post(
        "/source_material/upload/:id",
        APIV2Controller,
        :upload_media_version_file
      )

      get("/incidents", APIV2Controller, :incidents)
      get("/updates", APIV2Controller, :get_updates)
      post("/add_comment/:slug", APIV2Controller, :add_comment)
      post("/update/:slug/:attribute", APIV2Controller, :update)
    end
  end

  scope "/", PlatformWeb do
    get("/health_check", HealthCheckController, :index)
    # Will return non-200 status code after uptime is > 12 hours
    get("/health_check/exp", HealthCheckController, :exp)
  end

  scope "/spi", PlatformWeb do
    pipe_through([:browser, :require_authenticated_user])

    get("/users", SPIController, :user_search)
  end

  scope "/", PlatformWeb do
    pipe_through([:browser, :interstitial])

    get("/users/suspended", UserRegistrationController, :suspended)
    get("/users/no_access", UserRegistrationController, :no_access)
  end

  scope "/", PlatformWeb do
    pipe_through([:browser, :redirect_if_user_is_authenticated, :interstitial])

    get("/users/register", UserRegistrationController, :new)
    post("/users/register", UserRegistrationController, :create)

    get("/users/log_in", UserSessionController, :new)
    post("/users/log_in", UserSessionController, :create)
    get("/users/log_in/mfa", UserSessionController, :new_mfa)
    post("/users/log_in/mfa", UserSessionController, :create_mfa)

    get("/users/reset_password", UserResetPasswordController, :new)
    post("/users/reset_password", UserResetPasswordController, :create)
    get("/users/reset_password/:token", UserResetPasswordController, :edit)
    put("/users/reset_password/:token", UserResetPasswordController, :update)
  end

  scope "/", PlatformWeb do
    pipe_through([:browser, :interstitial])

    delete("/users/log_out", UserSessionController, :delete)
    get("/users/confirm", UserConfirmationController, :new)
    post("/users/confirm", UserConfirmationController, :create)
    get("/users/confirm/:token", UserConfirmationController, :edit)
    post("/users/confirm/:token", UserConfirmationController, :update)
  end

  scope "/", PlatformWeb do
    pipe_through([:browser, :require_authenticated_user, :interstitial_minimal])

    get("/users/onboarding", UserRegistrationController, :onboarding)
  end

  scope "/invite", PlatformWeb do
    pipe_through([:browser, :interstitial_minimal])

    get("/:code", InviteController, :new)
    get("/:code/sign_in_redirect", InviteController, :redirect_to_sign_in)
    post("/:code", InviteController, :accept)
  end

  scope "/", PlatformWeb do
    pipe_through([:browser, :require_authenticated_user, :app])

    # Redirect /map to avoid breaking old links
    get("/map", PageController, :index)
    get("/new", PageController, :new)
    get("/", PageController, :index)

    get("/users/settings", UserSettingsController, :edit)
    put("/users/settings", UserSettingsController, :update)
    get("/users/settings/confirm_email/:token", UserSettingsController, :confirm_email)

    post("/export/incidents", ExportController, :create_csv_export)
    post("/export/full", ExportController, :create_project_full_export)
    post("/export/backup_codes", ExportController, :create_backup_codes_export)

    live_session :default, on_mount: {MountHelperLive, :authenticated} do
      live("/settings", SettingsLive)
      live("/settings/mfa", SettingsLive.MFALive)
      live("/settings/backup_codes", SettingsLive.BackupCodesLive, :backupcode)

      live("/home", HomeLive.Index, :index)

      live("/incidents", MediaLive.Index)

      live("/incidents/:slug", MediaLive.Show, :show)
      live("/incidents/:slug/card", MediaLive.Card)
      live("/incidents/:slug/update/:attribute", MediaLive.Show, :edit)
      live("/incidents/:slug/history/:attribute", MediaLive.Show, :history)
      live("/incidents/:slug/upload", MediaLive.Show, :upload)
      live("/incidents/:slug/upload/merge", MediaLive.Show, :merge)
      live("/incidents/:slug/upload/copy", MediaLive.Show, :copy)
      live("/incidents/:slug/auto_metadata", MediaLive.Show, :auto_metadata)
      live("/incidents/:slug/detail/:scoped_id", MediaLive.Show, :media_version_detail)

      live("/projects", ProjectsLive.Index, :index)
      live("/projects/new", ProjectsLive.Index, :new)
      live("/projects/:id", ProjectsLive.Show, :overview)
      live("/projects/:id/map", ProjectsLive.Show, :map)
      live("/projects/:id/edit", ProjectsLive.Show, :edit)
      live("/projects/:id/access", ProjectsLive.Show, :access)
      live("/projects/:id/deleted", ProjectsLive.Show, :deleted)
      live("/projects/:id/queue", ProjectsLive.Show, :queue)

      live("/profile/:username", ProfilesLive.Show, :show)
      live("/profile/:username/assignments", ProfilesLive.Show, :assignments)
      live("/profile/:username/subscriptions", ProfilesLive.Show, :subscriptions)
      live("/profile/:username/edited", ProfilesLive.Show, :edited)
      live("/profile/:username/admin", ProfilesLive.Show, :admin)
      live("/profile/:username/admin/edit", ProfilesLive.Show, :admin_edit)

      live("/notifications", NotificationsLive)
    end

    live_session :admin, on_mount: {MountHelperLive, :admin} do
      live("/adminland/", AdminlandLive.Index, :activity)
      live("/adminland/users", AdminlandLive.Index, :users)
      live("/adminland/deleted", AdminlandLive.Index, :deleted)
      live("/adminland/activity", AdminlandLive.Index, :activity)
      live("/adminland/announcements", AdminlandLive.Index, :announcements)
      live("/adminland/security", AdminlandLive.Index, :security)
      live("/adminland/security/update", AdminlandLive.Index, :security_mode_create)
      live("/adminland/invites", AdminlandLive.Index, :invites)
      live("/adminland/api", AdminlandLive.Index, :api)
      live("/adminland/api/new", AdminlandLive.Index, :api_new)
    end
  end
end

platform/lib/platform_web/views/layout_view.ex
defmodule PlatformWeb.LayoutView do
  use PlatformWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

platform/lib/platform_web/templates/layout/_user_menu.html.heex
<ul>
  <%= if @current_user do %>
    <li><%= @current_user.email %></li>
    <li><%= link("Settings", to: Routes.user_settings_path(@conn, :edit)) %></li>
    <li><%= link("Log out", to: Routes.user_session_path(@conn, :delete), method: :delete) %></li>
  <% else %>
    <li><%= link("Register", to: Routes.user_registration_path(@conn, :new)) %></li>
    <li><%= link("Log in", to: Routes.user_session_path(@conn, :new)) %></li>
  <% end %>
</ul>

platform/lib/platform_web/templates/layout/interstitial.html.heex
<div class="min-h-screen flex justify-center py-12 sm:px-6 lg:px-8 items-center bg-neutral-600">
  <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-sm">
    <div class="text-center mb-8">
      <a href="/">
        <%!-- We put classes in a variable to avoid "Atlos" being put on its own line when autoformatted, which results in spacing issues. --%>
        <% classes =
          "px-1 py-px rounded-sm font-mono bg-neutral-200 text-neutral-600 font-bold text-3xl uppercase" %>
        <span class={classes}>Atlos</span>
        <br />
        <% name = Platform.Utils.get_instance_name() %>
        <%= if not is_nil(name) do %>
          <span class="font-mono md:text-sm uppercase font-medium text-white text-xl md:mt-1">
            <%= name %>
          </span>
        <% end %>
      </a>
    </div>
    <%= if not is_nil(assigns[:invite]) do %>
      <.card class="mb-8 overflow-hidden">
        <section :if={not is_nil(@invite)}>
          <.invitation_display invite={@invite} current_user={nil}>
            <div :if={not is_nil(@invite.project)} class="prose prose-sm text-center">
              <p>
                Create an Atlos account to join the project. If you already have an Atlos account, please <% redirect =
                  Routes.invite_path(@conn, :redirect_to_sign_in, @invite.code) %>
                <a href={redirect} class="text-button">sign in</a>
                to accept the invite.
              </p>
            </div>
          </.invitation_display>
        </section>
      </.card>
    <% end %>
    <.card header_class="bg-neutral-100" class="overflow-hidden">
      <:header>
        <p class="sec-head"><%= assigns[:title] || "" %></p>
      </:header>
      <%= if get(@flash, :info) do %>
        <p class="aside ~urge mb-4" role="alert"><%= get(@flash, :info) %></p>
      <% end %>
      <%= if get(@flash, :error) do %>
        <p class="aside ~critical mb-4" role="alert"><%= get(@flash, :error) %></p>
      <% end %>
      <%= @inner_content %>
    </.card>
    <div class="text-gray-300">
      <.footer_legal_language />
    </div>
  </div>
</div>

platform/lib/platform_web/templates/layout/interstitial_minimal.html.heex
<div class="min-h-screen flex flex justify-center py-4 sm:py-12 sm:px-6 lg:px-8 sm:items-center bg-neutral-600">
  <div class="mt-4 sm:mt-8 px-4 sm:mx-auto sm:w-full sm:max-w-md">
    <div class="text-center mb-8">
      <a href="/">
        <%!-- We put classes in a variable to avoid "Atlos" being put on its own line when autoformatted, which results in spacing issues. --%>
        <% classes =
          "px-1 py-px rounded-sm font-mono bg-neutral-200 text-neutral-600 font-bold text-3xl uppercase" %>
        <span class={classes}>Atlos</span>
        <br />
        <% name = Platform.Utils.get_instance_name() %>
        <%= if not is_nil(name) do %>
          <span class="font-mono md:text-sm uppercase font-medium text-white text-xl md:mt-1">
            <%= name %>
          </span>
        <% end %>
      </a>
    </div>
    <.card header_class="bg-neutral-100" class="overflow-hidden">
      <%= @inner_content %>
    </.card>
    <div class="text-gray-300">
      <.footer_legal_language />
    </div>
  </div>
</div>

platform/lib/platform_web/templates/layout/live.html.heex
<main class="h-full flex flex-col md:flex-row">
  <.nav
    path={@path}
    has_unread_notifications={Platform.Notifications.has_unread_notifications(@current_user)}
    current_user={@current_user}
    endpoint={@socket}
    live={true}
  />

  <div class="flex-1 flex flex-col overflow-hidden z-0">
    <div class={"mx-auto w-full " <> (if @full_width, do: "", else: "my-8")}>
      <div class={"mx-auto w-full " <> (if @full_width, do: "", else: "2xl:w-[1280px] min-h-[85vh]")}>
        <%= @inner_content %>
      </div>
      <div
        aria-live="assertive"
        class="fixed inset-0 z-[9999] flex items-end px-4 py-6 pointer-events-none sm:p-6 sm:items-start z-[100]"
      >
        <div class="w-full flex flex-col items-center space-y-4 sm:items-end">
          <% info = live_flash(@flash, :info) %>
          <%= if info do %>
            <.notification type="info">
              <%= raw(
                info
                |> Platform.Utils.render_markdown()
              ) %>
              <:right>
                <button
                  class="text-neutral-500 mt-1"
                  phx-click="lv:clear-flash"
                  phx-value-key="info"
                  type="button"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="h-4 w-4"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                      clip-rule="evenodd"
                    />
                  </svg>
                </button>
              </:right>
            </.notification>
          <% end %>

          <% error = live_flash(@flash, :error) %>
          <%= if error do %>
            <.notification type="error">
              <%= raw(
                error
                |> Platform.Utils.render_markdown()
              ) %>
              <:right>
                <button
                  class="text-neutral-500 mt-1"
                  phx-click="lv:clear-flash"
                  phx-value-key="error"
                  type="button"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="h-4 w-4"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                      clip-rule="evenodd"
                    />
                  </svg>
                </button>
              </:right>
            </.notification>
          <% end %>
        </div>
      </div>
      <div
        aria-live="assertive"
        class="fixed inset-0 bottom-0 flex items-end px-4 py-6 pointer-events-none sm:p-6 z-[100]"
      >
        <div class="w-full h-full flex flex-row-reverse space-y-4 items-end place-items-end">
          <.security_mode_notifications />
          <.notification
            :if={
              Platform.Billing.is_enabled?() and
                Platform.Billing.has_user_exceeded_edit_limit?(@current_user)
            }
            type="billing"
          >
            <span>
              <span class="font-medium">You've hit your monthly edit limit.</span>
              Please upgrade your plan to continue editing data on Atlos.
            </span>
            <.link to="/settings#billing" class="text-urge-500 font-medium block mt-4">
              Upgrade my account &rarr;
            </.link>
          </.notification>
        </div>
      </div>
    </div>
  </div>
</main>

platform/lib/platform_web/templates/layout/live_iframe.html.heex
<%= @inner_content %>

platform/lib/platform_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html
  lang="en"
  class={
    if assigns[:_no_background] == true, do: "scroll-smooth", else: "scroll-smooth bg-gray-50"
  }
>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/svg" href={Routes.static_path(@conn, "/images/icon.svg")} />
    <%= csrf_meta_tag() %>
    <.live_title suffix="| Atlos">
      <%= assigns[:title] || "Collaborative OSINT" %>
    </.live_title>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")} />
    <link
      phx-track-static
      rel="stylesheet"
      href={Routes.static_path(@conn, "/fonts/iosevka/iosevka.css")}
    />
    <link
      phx-track-static
      rel="stylesheet"
      href={Routes.static_path(@conn, "/fonts/inter/inter.css")}
    />
    <script
      defer
      phx-track-static
      type="text/javascript"
      src={Routes.static_path(@conn, "/assets/app.js")}
    >
    </script>
    <meta
      name="active_project_id"
      content={if assigns[:active_project], do: assigns[:active_project].id, else: nil}
    />
    <link href="https://unpkg.com/maplibre-gl@3.6.2/dist/maplibre-gl.css" rel="stylesheet" />
    <%= if assigns[:iframe_mode] do %>
      <base target="_parent" />
    <% end %>
    <%= if Platform.Billing.is_enabled?() do %>
      <script async src="https://js.stripe.com/v3/pricing-table.js">
      </script>
    <% end %>
    <%= if assigns[:current_user] do %>
      <style>
        [data-tag-target="<%= @current_user.username %>"] {
          background-color: #fde68a !important;
        }
      </style>
    <% end %>
    <%= if assigns[:connect_websocket] == false do %>
      <meta name="no-livesocket" content="true" />
    <% end %>
  </head>
  <body>
    <div id="tooltips"></div>
    <%= @inner_content %>
    <%= if not is_nil(System.get_env("HIGHLIGHT_CODE")) and (assigns[:iframe_mode] != true) do %>
      <script
        src="https://unpkg.com/highlight.run"
        data-code={System.get_env("HIGHLIGHT_CODE")}
        data-environment={Platform.Utils.get_instance_name()}
        data-version={Platform.Utils.get_instance_version()}
        id="highlight-script"
      >
      </script>
    <% end %>
  </body>
</html>

platform/lib/platform_web/templates/layout/workspace.html.heex
<div class="h-full flex">
    <div class="hidden w-28 bg-neutral-700 overflow-y-auto md:block">
    <div class="w-full py-6 flex flex-col items-center">
        <%= link to: "/", class: "flex flex-col items-center text-white" do %>
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <span class="text-white uppercase font-bold">Atlos</span>
        <%= end %>
        <div class="flex-1 mt-6 w-full px-2 space-y-1">
        <a href="#" class="bg-neutral-800 text-white group w-full p-3 rounded-md flex flex-col items-center text-xs font-medium" aria-current="page">
            <svg class="text-white group-hover:text-white h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 4v16m8-8H4" />
            </svg>
            <span class="mt-2">New</span>
        </a>

        <a href="#" class="text-neutral-100 hover:bg-neutral-800 hover:text-white group w-full p-3 rounded-md flex flex-col items-center text-xs font-medium">
            <svg class="text-neutral-300 group-hover:text-white h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zM14 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zM14 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z" />
            </svg>
            <span class="mt-2">Queue</span>
        </a>

        <a href="#" class="text-neutral-100 hover:bg-neutral-800 hover:text-white group w-full p-3 rounded-md flex flex-col items-center text-xs font-medium">
            <svg class="text-neutral-300 group-hover:text-white h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
            </svg>
            <span class="mt-2">All Media</span>
        </a>

        <a href="#" class="text-neutral-100 hover:bg-neutral-800 hover:text-white group w-full p-3 rounded-md flex flex-col items-center text-xs font-medium">
            <svg class="text-neutral-300 group-hover:text-white h-6 w-6" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
            </svg>
            <span class="mt-2">Watchlist</span>
        </a>


        <.navlink to="/" label="Notifications">
            <svg class="text-neutral-300 group-hover:text-white h-6 w-6" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
            </svg>
        </.navlink>

        <.navlink to={Routes.user_settings_path(@conn, :edit)} label="Settings">
            <svg class="text-neutral-300 group-hover:text-white h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
            </svg>
        </.navlink>
        </div>
    </div>
    </div>

    <div class="flex-1 flex flex-col overflow-hidden">
        <div class="m-8">
            <%= @inner_content %>
            <div aria-live="assertive" class="fixed inset-0 flex items-end px-4 py-6 pointer-events-none sm:p-6 sm:items-start">
                <div class="w-full flex flex-col items-center space-y-4 sm:items-end">
                    <% info = get_flash(@conn, :info) %>
                    <%= if info do %>
                        <.notification type="info">
                            <%= info %>
                        </.notification>
                    <% end %>

                    <% error = get_flash(@conn, :error) %>
                    <%= if error do %>
                        <.notification type="error">
                            <%= error %>
                        </.notification>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>